### ISSUE TITLE
error running download_extractor.sh

### ISSUE THREAD

**Issue by meongeun** [yh2371/CoMo#1]
There are errors running download_extractor.sh commands. 
Does the link have permission to anyone? please check once again. 

Access denied with the following error:

 	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses. 

You may still be able to access the file from the browser:

	 https://drive.google.com/uc?id=1o7RTDQcToJjTm9_mNWTyzvZvjTWpZfug

Also in the training codes : train_dec.py, train_t2m.py 
Is the data_opt_path for t2m folder name "Comp_v6_KLD005/"? because downloading the t2m.zip file from text-to-motion github has the folder name Comp_v6_KLD01/.

**Comment by yh2371** [comment]
The link has been updated, if you've downloaded t2m.zip from the text-to-motion repo, please feel free to change the path accordingly. Thanks for pointing this out!
