### ISSUE TITLE
file not found error in checkpoints/t2m/

### ISSUE THREAD

**Issue by meongeun** [yh2371/CoMo#2]
Where can i get VQVAEV3_CB1024_CMT_H1024_NRES3 folder? 
I'm getting this error. 

FileNotFoundError: [Errno 2] No such file or directory: 'checkpoints/t2m/VQVAEV3_CB1024_CMT_H1024_NRES3/meta/mean.npy'

**Comment by yh2371** [comment]
Hi, the t2m.zip downloaded from the updated link #1 should contain this folder

**Comment by Lucky1192405754** [comment]
Hi there, 
thanks for your amazing work, but I also face the same problem with missing file in ./checkpoints/t2mQVAEV3_CB1024_CMT_H1024_NRES3/meta/mean.npy here when I tried to reproduce your evaluation...

Specifically, the provided Google drive link in [https://github.com/yh2371/CoMo/issues/1](url) has been expired, and there is no VQVAEV3_CB1024_CMT_H1024_NRES3 folder in latest t2m.zip from the official link, which is also listed in your download_extractor.sh.  I'd like to know if there is another way to obtain this file.

Sincerely appreciate for your concern, best wishes.
